# Generated by Django 5.2.17 on 2026-10-04 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_test_options_test_difficulty_test_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id_snapshot', models.PositiveBigIntegerField()),
                ('question_text', models.TextField()),
                ('selected_text', models.TextField(blank=True)),
                ('correct_text', models.TextField()),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение ответа')),
                ('is_correct', models.BooleanField()),
                ('options', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-completed_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Раздел теста', 'verbose_name_plural': 'Разделы тестов'},
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Объяснение ответа'),
        ),
        migrations.AddField(
            model_name='test',
            name='demo_key',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='attempt_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='title_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, verbose_name='Рекомендуемое время (минуты)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.CharField(choices=[('math', 'Математика'), ('history', 'История'), ('it', 'Информационные технологии'), ('python', 'Python'), ('sql', 'SQL'), ('web', 'Web / HTTP'), ('testing', 'Тестирование ПО')], default='math', max_length=10, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.test'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.CheckConstraint(condition=models.Q(('total__isnull', True), ('score__lte', models.F('total')), _connector='OR'), name='result_score_within_total'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tasks.testresult'),
        ),
        migrations.AddField(
            model_name='attemptdraft',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.test'),
        ),
        migrations.AddField(
            model_name='attemptdraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('result', 'question_id_snapshot'), name='one_response_per_question'),
        ),
    ]
